FROM openjdk:8
ADD target/notification-service.jar notification-service.jar
EXPOSE 9004
ENTRYPOINT ["java", "-jar", "notification-service.jar"]curity.egd=file:/dev/./urandom -jar /notification-service.jar" ]